AddonId: 'ReXBOXSX'
Packages:
  - Version: 1.0
    RequiredApiVersion: 2.3.0
    ReleaseDate: 2022-10-04
    PackageUrl: https://github.com/TheKersalMassive/ReskinXBOXSX/releases/download/v1.0/ReXBOXSX_1_0.pthm
    Changelog:
      - Initial release for Playnite
      - Please read the FAQ before raising any issues on GitHub or Discord
